name: Bug Report
description: File a bug report.
title: "Summarize the bug"
labels: ["bug"]
projects: ["brobeson/9"]
assignees: ["brobeson"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What is the expected behavior?
      placeholder: Describe the behavior that you expected.
    validations:
      required: true
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What is the actual behavior?
      placeholder: Describe the behavior that actually occurred.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Reproduction Steps
      description: How can others reproduce the bug?
      placeholder: List the steps to reproduce the bug.
    validations:
      required: true
