name: New Feature
description: Request a new feature
title: "Summarize the new feature"
labels: ["enhancement"]
projects: ["brobeson/9"]
assignees: ["brobeson"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to request a new feature!
  - type: textarea
    id: feature
    attributes:
      label: New Feature
      description: What is the new feature?
      placeholder: Please provide as much detail as possible.
    validations:
      required: true
